baseURL = "https://blog.lwp2070809.de/"
languageCode = "zh-cn"
title = "一只孤独的河豚"
copyright = "lwp2070809"
theme = "hugo-theme-stack"

DefaultContentLanguage = "zh"
hasCJKLanguage = true

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
