[zh]
    languageName = "中文"
    title = "一只孤独的河豚"
    weight = 1
    [zh.params.sidebar]
        subtitle = "Tempus timendum est mihi."

[en]
    languageName = "English"
    disabled = true
    title = "Y一只孤独的河豚"
    weight = 2
    [en.params.sidebar]
        subtitle = "Tempus timendum est mihi."
